
server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: I

  datasource:
    url: jdbc:mysql://localhost/dukjins
    username: root
    password: DBcodus1206^^
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
